//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAssetBundle
{
    
    public class Archery
    {
        public const string BundleName = "archery";
        public const string ARCHERYPREFAB = "archeryprefab";
        public const string ARCHERY_ARROW = "archery_arrow";
        public const string ARCHERY_BOW = "archery_bow";
        public const string ARCHERY_GOTCHA = "archery_gotcha";
        public const string ARCHERY_HEART = "archery_heart";
        public const string ARCHERY_HEARTS = "archery_hearts";
        public const string ARCHERY_PERSON = "archery_person";
        public const string ARCHERY_REDHOLE = "archery_redhole";
        public const string ARCHERY_XIAN_DOWN = "archery_xian_down";
        public const string ARCHERY_XIAN_DOWNTIPS = "archery_xian_downtips";
        public const string ARCHERY_XIAN_NORMAL = "archery_xian_normal";
        public const string ARCHERY_XIAN_START = "archery_xian_start";
    }
    public class Atm_bright_prefab
    {
        public const string BundleName = "atm_bright_prefab";
        public const string ATM_BRIGHT = "atm_bright";
    }
    public class Atm_cloud_prefab
    {
        public const string BundleName = "atm_cloud_prefab";
        public const string ATM_CLOUD = "atm_cloud";
    }
    public class Atm_crystalball_prefab
    {
        public const string BundleName = "atm_crystalball_prefab";
        public const string ATM_CRYSTAL = "atm_crystal";
    }
    public class Atm_love_prefab
    {
        public const string BundleName = "atm_love_prefab";
        public const string ATM_LOVE = "atm_love";
    }
    public class Atm_romantic_prefab
    {
        public const string BundleName = "atm_romantic_prefab";
        public const string ATM_ROMANTIC = "atm_romantic";
    }
    public class Atm_stun_prefab
    {
        public const string BundleName = "atm_stun_prefab";
        public const string ATM_STUN = "atm_stun";
    }
    public class Atm_sun_prefab
    {
        public const string BundleName = "atm_sun_prefab";
        public const string ATM_SUN = "atm_sun";
    }
    public class Award
    {
        public const string BundleName = "award";
        public const string AWARDPREFAB = "awardprefab";
        public const string AWARD_FEEDBACK = "award_feedback";
        public const string COLLECT_DONE = "collect_done";
        public const string GUIDE_ACTION_STAR = "guide_action_star";
        public const string IMG_TITLE_AWARD = "img_title_award";
        public const string REWARD_GUIDE_GET = "reward_guide_get";
        public const string REWARD_GUIDE_UNGET = "reward_guide_unget";
        public const string WATCHCHAPTER_BG = "watchchapter_bg";
    }
    public class Barbecue
    {
        public const string BundleName = "barbecue";
        public const string BROKEN1 = "broken1";
        public const string BROKEN2 = "broken2";
        public const string BROKEN3 = "broken3";
        public const string BROKEN4 = "broken4";
        public const string BROKEN5 = "broken5";
        public const string BROKEN6 = "broken6";
        public const string BROKEN7 = "broken7";
        public const string BROKEN8 = "broken8";
        public const string COLORFLOWERS = "colorflowers";
        public const string BROKEN_1 = "broken_1";
        public const string BROKEN_2 = "broken_2";
        public const string BROKEN_3 = "broken_3";
        public const string BROKEN_4 = "broken_4";
        public const string BROKEN_5 = "broken_5";
        public const string BROKEN_6 = "broken_6";
        public const string BROKEN_7 = "broken_7";
        public const string BROKEN_8 = "broken_8";
        public const string FIRE = "fire";
        public const string SMOKE = "smoke";
        public const string STAR = "star";
        public const string FIREPREFAB = "fireprefab";
        public const string HITEFFECT = "hiteffect";
        public const string SMOKEPREFAB = "smokeprefab";
        public const string FIRE_SHADOW = "fire_shadow";
        public const string SMOKE_SHADOW = "smoke_shadow";
        public const string SPARKLE = "sparkle";
        public const string TEXTURE_SMOKE = "texture_smoke";
        public const string TEXTURE_SMOKEMASK = "texture_smokemask";
        public const string TEXTURE_STAR = "texture_star";
        public const string BARBECUE_BALLOON = "barbecue_balloon";
        public const string BARBECUE_FIRE = "barbecue_fire";
        public const string BARBECUE_INGREDIENTS = "barbecue_ingredients";
        public const string BARBECUEPREFAB = "barbecueprefab";
        public const string ADD_ONE = "add_one";
        public const string BALLOON_FINNISH = "balloon_finnish";
        public const string BALLOON_UNFINISH = "balloon_unfinish";
        public const string BALLOONS_COLOR = "balloons_color";
        public const string BALLOONS_UN = "balloons_un";
        public const string BROCCOLI = "broccoli";
        public const string CHOOSE_RIGHT = "choose_right";
        public const string COLOR_DOT = "color_dot";
        public const string FIRE_DOT = "fire_dot";
        public const string FIRE_LINE = "fire_line";
        public const string FIRE_TOP = "fire_top";
        public const string FIRE_UN = "fire_un";
        public const string FISH = "fish";
        public const string FLINT = "flint";
        public const string FLINT_OTHER = "flint_other";
        public const string FLINT_SHADOW = "flint_shadow";
        public const string FLINT_UNPRESSED = "flint_unpressed";
        public const string ICON_FALSE = "icon_false";
        public const string INGREDIENTS = "ingredients";
        public const string INGREDIENTS_FINISH = "ingredients_finish";
        public const string LOCK = "lock";
        public const string MASK_BOTTOM = "mask_bottom";
        public const string MEAT = "meat";
        public const string PLATE = "plate";
        public const string PREPAIR_TOP = "prepair_top";
        public const string ROLE_TOAST = "role_toast";
        public const string SMOKE_1 = "smoke_1";
        public const string SMOKE_2 = "smoke_2";
    }
    public class Boxeffect
    {
        public const string BundleName = "boxeffect";
        public const string GIFBOXANIMATIOR = "gifboxanimatior";
        public const string IDLE = "idle";
        public const string OPEN = "open";
        public const string MATFLASH = "matflash";
        public const string MATHEAD1 = "mathead1";
        public const string MATSHARP = "matsharp";
        public const string MATSHINE1 = "matshine1";
        public const string MATSTAR = "matstar";
        public const string UI_MASKDEFAULT = "ui_maskdefault";
        public const string GIFTBOX = "giftbox";
        public const string MASKADDITIVE = "maskadditive";
        public const string MASKDEFAULT = "maskdefault";
        public const string BOX1 = "box1";
        public const string BOX2 = "box2";
        public const string BOX3 = "box3";
        public const string BOX4 = "box4";
        public const string TXTFLASH = "txtflash";
        public const string TXTHEAD1 = "txthead1";
        public const string TXTSHARP = "txtsharp";
        public const string TXTSHINE1 = "txtshine1";
        public const string TXTSTAR = "txtstar";
        public const string BOXEFFECTPREFAB = "boxeffectprefab";
    }
    public class Buydiamonds
    {
        public const string BundleName = "buydiamonds";
        public const string BUYDIAMONDSPREFAB = "buydiamondsprefab";
        public const string IMG_TITLE_DIAMOND = "img_title_diamond";
        public const string SHOP_ITEMBG = "shop_itembg";
    }
    public class Checkemail
    {
        public const string BundleName = "checkemail";
        public const string CHECKEMAILPREFAB = "checkemailprefab";
    }
    public class Choicepass
    {
        public const string BundleName = "choicepass";
        public const string CHOICEITEM = "choiceitem";
        public const string CHOICEPASSPREFAB = "choicepassprefab";
        public const string CHOICE_ITEM_BG = "choice_item_bg";
        public const string IC_BLANK = "ic_blank";
    }
    public class Choicepasschangetips
    {
        public const string BundleName = "choicepasschangetips";
        public const string CHOICEPASSCHANGETIPSPREFAB = "choicepasschangetipsprefab";
    }
    public class Chooseavatar
    {
        public const string BundleName = "chooseavatar";
        public const string CHOOSEAVATARPREFAB = "chooseavatarprefab";
    }
    public class Comfirmname_prefab
    {
        public const string BundleName = "comfirmname_prefab";
        public const string CONFIRMNAME = "confirmname";
    }
    public class Commonres
    {
        public const string BundleName = "commonres";
        public const string RAPIDBLUREFFECT = "rapidblureffect";
        public const string BLURPREFAB = "blurprefab";
        public const string CAPTUREPREFAB = "captureprefab";
        public const string SIMULATION = "simulation";
        public const string STARTON = "starton";
        public const string TIPSDIALOG = "tipsdialog";
        public const string TOAST = "toast";
        public const string WEBDIALOG = "webdialog";
        public const string APP_ICON = "app_icon";
        public const string BTN_CLOSE = "btn_close";
        public const string BTN_DISABLE_116 = "btn_disable_116";
        public const string BTN_NORMAL_104 = "btn_normal_104";
        public const string BTN_NORMAL_116 = "btn_normal_116";
        public const string BTN_PRESSED_116 = "btn_pressed_116";
        public const string BUTTON_S_100 = "button_s_100";
        public const string BUTTON_S_PRESSED_100 = "button_s_pressed_100";
        public const string BUTTON_S_UNIMPORTANCE_100 = "button_s_unimportance_100";
        public const string BUTTON_S_UNIMPORTANCE_PRESSED_100 = "button_s_unimportance_pressed_100";
        public const string CIRCULAR = "circular";
        public const string COM_BTN_BACK = "com_btn_back";
        public const string COM_SINGLE_COLOR = "com_single_color";
        public const string COM_TITLE_FRAME = "com_title_frame";
        public const string COM_TOAST_FRAME_1 = "com_toast_frame_1";
        public const string COMM_POP_BG = "comm_pop_bg";
        public const string DEFAULT_COVER = "default_cover";
        public const string DEFAULT_LOGO = "default_logo";
        public const string ICON_CHOICE = "icon_choice";
        public const string ICON_DIAMOND = "icon_diamond";
        public const string ICON_ROSE_COIN = "icon_rose_coin";
        public const string ICON_TICKET = "icon_ticket";
        public const string PROGRESS_BAR = "progress_bar";
        public const string PROGRESS_BAR_BOTTOM = "progress_bar_bottom";
        public const string START_SPLASH = "start_splash";
        public const string STORY_BANNER_BG = "story_banner_bg";
        public const string STORY_DEFAULT_BG = "story_default_bg";
        public const string TOAST_BG = "toast_bg";
    }
    public class Daypass
    {
        public const string BundleName = "daypass";
        public const string DAYPASSPREFAB = "daypassprefab";
        public const string DAYPASS_EFFECT = "daypass_effect";
        public const string ICON_DAYPASS = "icon_daypass";
        public const string PURCHASE_ONE = "purchase_one";
        public const string STAGE = "stage";
        public const string TITLE_DAYPASS = "title_daypass";
        public const string TRANGLE_BOOK = "trangle_book";
    }
    public class Emaillogin
    {
        public const string BundleName = "emaillogin";
        public const string EMAILLOGINPREFAB = "emailloginprefab";
        public const string EMAIL_TOPBAR = "email_topbar";
        public const string IC_SIGN_SEE_0 = "ic_sign_see_0";
        public const string IC_SIGN_SEE_1 = "ic_sign_see_1";
    }
    public class Feedback
    {
        public const string BundleName = "feedback";
        public const string FEEDBACKPREFAB = "feedbackprefab";
        public const string FRAME_FEEDBACK_INPUT = "frame_feedback_input";
        public const string IC_FEEDBACK_ADD = "ic_feedback_add";
        public const string IC_FEEDBACK_CLOSE = "ic_feedback_close";
        public const string IC_SELECT_SINGLE_0 = "ic_select_single_0";
        public const string IC_SELECT_SINGLE_1 = "ic_select_single_1";
    }
    public class Female
    {
        public const string BundleName = "female";
        public const string FEMALEBASE = "femalebase";
        public const string FEMALEBASE_ATLAS = "femalebase_atlas";
        public const string FEMALEBASE_MATERIAL = "femalebase_material";
        public const string FEMALEPREFAB = "femaleprefab";
        public const string FEMALESKELETON = "femaleskeleton";
        public const string FEMALESKELETON_SKELETONDATA = "femaleskeleton_skeletondata";
    }
    public class Female_bd
    {
        public const string BundleName = "female_bd";
        public const string BD_FEMALEBASE = "bd_femalebase";
        public const string BD_FEMALEBASE_ATLAS = "bd_femalebase_atlas";
        public const string BD_FEMALEBASE_MATERIAL = "bd_femalebase_material";
        public const string BD_FEMALEBASE_SKELETONDATA = "bd_femalebase_skeletondata";
        public const string FEMALE_BDPREFAB = "female_bdprefab";
    }
    public class Female_cupid
    {
        public const string BundleName = "female_cupid";
        public const string FEMALE_CUPIDPREFAB = "female_cupidprefab";
        public const string QIUBITE_FEMALEBASE = "qiubite_femalebase";
        public const string QIUBITE_FEMALEBASE_ATLAS = "qiubite_femalebase_atlas";
        public const string QIUBITE_FEMALEBASE_MATERIAL = "qiubite_femalebase_material";
        public const string QIUBITE_FEMALEBASE_SKELETONDATA = "qiubite_femalebase_skeletondata";
    }
    public class Female_rmbh
    {
        public const string BundleName = "female_rmbh";
        public const string FEMALE_RMBHPREFAB = "female_rmbhprefab";
        public const string RMBH_FEMALEBASE = "rmbh_femalebase";
        public const string RMBH_FEMALEBASE_ATLAS = "rmbh_femalebase_atlas";
        public const string RMBH_FEMALEBASE_MATERIAL = "rmbh_femalebase_material";
        public const string RMBH_FEMALEBASE_SKELETONDATA = "rmbh_femalebase_skeletondata";
    }
    public class Loading
    {
        public const string BundleName = "loading";
        public const string LOADINGPREFAB = "loadingprefab";
        public const string LOAD_WEAK = "load_weak";
        public const string LOADING_PAGE = "loading_page";
    }
    public class Lobby
    {
        public const string BundleName = "lobby";
        public const string DISCOVER = "discover";
        public const string STORYITEM = "storyitem";
        public const string LIBRARY = "library";
        public const string LOBBYPREFAB = "lobbyprefab";
        public const string TOPINFOBAR = "topinfobar";
        public const string BANNERCOVER = "bannercover";
        public const string DAYPASS_INBTN = "daypass_inbtn";
        public const string DIS_TAB_SELECT = "dis_tab_select";
        public const string DISCOVER_LINE = "discover_line";
        public const string DISCOVER_NEWS = "discover_news";
        public const string ICON_DISCOVER_NORMAL = "icon_discover_normal";
        public const string ICON_DISCOVER_SELECTED = "icon_discover_selected";
        public const string ICON_REWARDS = "icon_rewards";
        public const string LOBBY_FRAME = "lobby_frame";
        public const string LOBBY_LOGO_TOPBAR = "lobby_logo_topbar";
        public const string PROGRESSBAR_STORY = "progressbar_story";
        public const string PROGRESSBAR_STORY_BOTTOM = "progressbar_story_bottom";
        public const string STORY_BG_WHITE = "story_bg_white";
        public const string STORY_TAB_HOT = "story_tab_hot";
        public const string STORY_TAB_NEW = "story_tab_new";
        public const string STORY_TAB_UPDATE = "story_tab_update";
        public const string STORYS_BG_GREY = "storys_bg_grey";
        public const string STORYS_SCORE_BG = "storys_score_bg";
        public const string TIMER_STATUS = "timer_status";
        public const string TIPS_BOTTOM_BG = "tips_bottom_bg";
        public const string TOPBAR = "topbar";
    }
    public class Male
    {
        public const string BundleName = "male";
        public const string MALEBASE = "malebase";
        public const string MALEBASE_ATLAS = "malebase_atlas";
        public const string MALEBASE_MATERIAL = "malebase_material";
        public const string MALEBASE_SKELETONDATA = "malebase_skeletondata";
        public const string MALEPREFAB = "maleprefab";
    }
    public class Male_bd
    {
        public const string BundleName = "male_bd";
        public const string BD_MALEBASE = "bd_malebase";
        public const string BD_MALEBASE_ATLAS = "bd_malebase_atlas";
        public const string BD_MALEBASE_MATERIAL = "bd_malebase_material";
        public const string BD_MALEBASE_SKELETONDATA = "bd_malebase_skeletondata";
        public const string MALE_BDPREFAB = "male_bdprefab";
    }
    public class Male_cupid
    {
        public const string BundleName = "male_cupid";
        public const string MALE_CUPIDPREFAB = "male_cupidprefab";
        public const string QIUBITE_MALEBASE = "qiubite_malebase";
        public const string QIUBITE_MALEBASE_ATLAS = "qiubite_malebase_atlas";
        public const string QIUBITE_MALEBASE_MATERIAL = "qiubite_malebase_material";
        public const string QIUBITE_MALEBASE_SKELETONDATA = "qiubite_malebase_skeletondata";
    }
    public class Male_rmbh
    {
        public const string BundleName = "male_rmbh";
        public const string MALE_RMBHPREFAB = "male_rmbhprefab";
        public const string RMBH_MALEBASE = "rmbh_malebase";
        public const string RMBH_MALEBASE_ATLAS = "rmbh_malebase_atlas";
        public const string RMBH_MALEBASE_MATERIAL = "rmbh_malebase_material";
        public const string RMBH_MALEBASE_SKELETONDATA = "rmbh_malebase_skeletondata";
    }
    public class Messages
    {
        public const string BundleName = "messages";
        public const string MESSAGESPREFAB = "messagesprefab";
        public const string IC_BLANK = "ic_blank";
    }
    public class Npc
    {
        public const string BundleName = "npc";
        public const string NPCPREFAB = "npcprefab";
    }
    public class Plotinteraction
    {
        public const string BundleName = "plotinteraction";
        public const string BATTLE = "battle";
        public const string FORWARD = "forward";
        public const string INTERACTION_WEREWOLF_1 = "interaction_werewolf_1";
        public const string INTERACTION_WEREWOLF_2 = "interaction_werewolf_2";
        public const string INTERACTION_WEREWOLF_3 = "interaction_werewolf_3";
        public const string BLOW_CANDLES_FLAME_NORMAL = "blow_candles_flame_normal";
        public const string BLOW_CANDLES_FLAME_SHAKE = "blow_candles_flame_shake";
        public const string BLOW_CANDLES_SMOKE = "blow_candles_smoke";
        public const string BLOWCANDLESANIM = "blowcandlesanim";
        public const string BLOWCANDLES = "blowcandles";
        public const string BLOWCANDLESANIMPREFAB = "blowcandlesanimprefab";
        public const string BLOW_CANDLES_CAKE = "blow_candles_cake";
        public const string BLOW_CANDLES_FLAME_1 = "blow_candles_flame_1";
        public const string BLOW_CANDLES_FLAME_2 = "blow_candles_flame_2";
        public const string BLOW_CANDLES_FLAME_3 = "blow_candles_flame_3";
        public const string BLOW_CANDLES_FLAME_4 = "blow_candles_flame_4";
        public const string BLOW_CANDLES_FLAME_5 = "blow_candles_flame_5";
        public const string BLOW_CANDLES_FLAME_6 = "blow_candles_flame_6";
        public const string BLOW_CANDLES_FLAME_7 = "blow_candles_flame_7";
        public const string BLOW_CANDLES_FLAME_8 = "blow_candles_flame_8";
        public const string BLOW_CANDLES_FLAME_9 = "blow_candles_flame_9";
        public const string BLOW_CANDLES_FLAME_10 = "blow_candles_flame_10";
        public const string BLOW_CANDLES_FLAME_11 = "blow_candles_flame_11";
        public const string BLOW_CANDLES_FLAME_12 = "blow_candles_flame_12";
        public const string BLOW_CANDLES_SMOKE_1 = "blow_candles_smoke_1";
        public const string BLOW_CANDLES_SMOKE_2 = "blow_candles_smoke_2";
        public const string BLOW_CANDLES_SMOKE_3 = "blow_candles_smoke_3";
        public const string BLOW_CANDLES_SMOKE_4 = "blow_candles_smoke_4";
        public const string BLOW_CANDLES_SMOKE_5 = "blow_candles_smoke_5";
        public const string BLOW_CANDLES_SMOKE_6 = "blow_candles_smoke_6";
        public const string BLOW_CANDLES_SMOKE_7 = "blow_candles_smoke_7";
        public const string BLOW_CANDLES_SMOKE_8 = "blow_candles_smoke_8";
        public const string CHEERS = "cheers";
        public const string INTERACTION_CHEER_1 = "interaction_cheer_1";
        public const string INTERACTION_CHEER_2 = "interaction_cheer_2";
        public const string INTERACTION_CHEER_3 = "interaction_cheer_3";
        public const string INTERACTION_CHEER_4 = "interaction_cheer_4";
        public const string INTERACTION_CHERR_5 = "interaction_cherr_5";
        public const string CUTCAKE = "cutcake";
        public const string CUT_CAKE_IMG_1 = "cut_cake_img_1";
        public const string CUT_CAKE_IMG_2 = "cut_cake_img_2";
        public const string CUT_CAKE_IMG_3 = "cut_cake_img_3";
        public const string CUT_CAKE_LINE = "cut_cake_line";
        public const string FINDROOM = "findroom";
        public const string INTERACTION_FIND_ROOM_ERROR = "interaction_find_room_error";
        public const string INTERACTION_FIND_ROOM_FRAME = "interaction_find_room_frame";
        public const string FINDTHINGS = "findthings";
        public const string FINDTHINGSSUCCESS = "findthingssuccess";
        public const string FIND_THINGS_BTN_ICON_2 = "find_things_btn_icon_2";
        public const string FIND_THINGS_BTN_ICON_3 = "find_things_btn_icon_3";
        public const string FIND_THINGS_FRAME_1 = "find_things_frame_1";
        public const string FIND_THINGS_FRAME_2 = "find_things_frame_2";
        public const string FIND_THINGS_ICON_1 = "find_things_icon_1";
        public const string FIND_THINGS_ICON_2 = "find_things_icon_2";
        public const string FIND_THINGS_ICON_3 = "find_things_icon_3";
        public const string GUESSTHINGS = "guessthings";
        public const string GUESS_THINGS_ICON_1 = "guess_things_icon_1";
        public const string GUESS_THINGS_ICON_2 = "guess_things_icon_2";
        public const string GUESS_THINGS_ICON_3 = "guess_things_icon_3";
        public const string GUESS_THINGS_ICON_4 = "guess_things_icon_4";
        public const string GUESS_THINGS_ICON_5 = "guess_things_icon_5";
        public const string GUESS_THINGS_ICON_6 = "guess_things_icon_6";
        public const string GUESS_THINGS_TITLE = "guess_things_title";
        public const string JIGSAW = "jigsaw";
        public const string JIGSAW_FRAME_1 = "jigsaw_frame_1";
        public const string JIGSAW_FRAME_2 = "jigsaw_frame_2";
        public const string JIGSAW_IMG_1 = "jigsaw_img_1";
        public const string JIGSAW_IMG_2 = "jigsaw_img_2";
        public const string JIGSAW_IMG_3 = "jigsaw_img_3";
        public const string JIGSAW_IMG_4 = "jigsaw_img_4";
        public const string JIGSAW_IMG_5 = "jigsaw_img_5";
        public const string JIGSAW_IMG_6 = "jigsaw_img_6";
        public const string JIGSAW_IMG_7 = "jigsaw_img_7";
        public const string JIGSAW_IMG_8 = "jigsaw_img_8";
        public const string JIGSAW_IMG_9 = "jigsaw_img_9";
        public const string JIGSAW_TITLE = "jigsaw_title";
        public const string KISS = "kiss";
        public const string KISS_ICON = "kiss_icon";
        public const string KISS_TIPS = "kiss_tips";
        public const string BORDEREFFECTMATERIAL = "bordereffectmaterial";
        public const string BORDEREFFECTSHADER = "bordereffectshader";
        public const string BORDER = "border";
        public const string LONGPRESS = "longpress";
        public const string LOOKSOMEWHERE = "looksomewhere";
        public const string LOOK_SOMEWHERE_ICON_1 = "look_somewhere_icon_1";
        public const string LOOK_SOMEWHERE_ICON_2 = "look_somewhere_icon_2";
        public const string LOOK_SOMEWHERE_ICON_3 = "look_somewhere_icon_3";
        public const string LOOK_SOMEWHERE_ICON_4 = "look_somewhere_icon_4";
        public const string OPENEYES = "openeyes";
        public const string INTERACTION_OPEN_EYE_MASK = "interaction_open_eye_mask";
        public const string REBUKE = "rebuke";
        public const string REBUKE_FRAME_1 = "rebuke_frame_1";
        public const string REBUKE_FRAME_2 = "rebuke_frame_2";
        public const string REBUKE_FRAME_3 = "rebuke_frame_3";
        public const string SPRITE_HEAD_MATE = "sprite_head_mate";
        public const string SPRITE_STAR_MAT = "sprite_star_mat";
        public const string DISAPPEARPARTICLE = "disappearparticle";
        public const string SPRITE_HEAD = "sprite_head";
        public const string SPRITE_STAR = "sprite_star";
        public const string FLY_MAT_STAR_00 = "fly_mat_star_00";
        public const string FLY_TXT_STAR_00 = "fly_txt_star_00";
        public const string SPRITEFLY = "spritefly";
        public const string STROK_ANIM_HEART = "strok_anim_heart";
        public const string STROK_ANIM_PARTICLE = "strok_anim_particle";
        public const string STROK_ANIM_STAR = "strok_anim_star";
        public const string STROKEPARTICLE = "strokeparticle";
        public const string HEART_STROK_IMG = "heart_strok_img";
        public const string STAR_LIGHT_IMG = "star_light_img";
        public const string STAR_STROK_IMG = "star_strok_img";
        public const string PLAY = "play";
        public const string STROKEANIMATOR = "strokeanimator";
        public const string STROKEANIMATION = "strokeanimation";
        public const string FINGER = "finger";
        public const string STROKING = "stroking";
        public const string STROKINGFAIRY = "strokingfairy";
        public const string STROKINGWOLF = "strokingwolf";
        public const string SWITCHSCENE = "switchscene";
        public const string ADDHEART = "addheart";
        public const string ARROW = "arrow";
        public const string BG_PINK = "bg_pink";
        public const string FIND_THINGS_ERROR = "find_things_error";
        public const string FIND_THINGS_OK = "find_things_ok";
        public const string HEART_ANIM_PROGRESS = "heart_anim_progress";
        public const string HEART_PURPE = "heart_purpe";
        public const string INTERACTION_ATTACK_BTN_INNER = "interaction_attack_btn_inner";
        public const string INTERACTION_ATTACK_BTN_OUTER = "interaction_attack_btn_outer";
        public const string INTERACTION_ATTACK_BTN_PRESSED = "interaction_attack_btn_pressed";
        public const string INTERACTION_ATTACK_EFFECT_1 = "interaction_attack_effect_1";
        public const string INTERACTION_ATTACK_EFFECT_2 = "interaction_attack_effect_2";
        public const string INTERACTION_ATTACK_EFFECT_3 = "interaction_attack_effect_3";
        public const string INTERACTION_BORDER = "interaction_border";
        public const string INTERACTION_BTN_FINGER = "interaction_btn_finger";
        public const string INTERACTION_BTN_SKIP_NORMAL = "interaction_btn_skip_normal";
        public const string INTERACTION_BTN_SKIP_PRESSED = "interaction_btn_skip_pressed";
        public const string INTERACTION_COUNTDOWN_CIRCLE_BG = "interaction_countdown_circle_bg";
        public const string INTERACTION_HEART_EMPTY = "interaction_heart_empty";
        public const string INTERACTION_HEART_GRAY = "interaction_heart_gray";
        public const string INTERACTION_HEART_SMALL = "interaction_heart_small";
        public const string INTERACTION_NORMAL_BTN_INNER = "interaction_normal_btn_inner";
        public const string INTERACTION_NORMAL_BTN_OUTER = "interaction_normal_btn_outer";
        public const string INTERACTION_NORMAL_BTN_PRESSED = "interaction_normal_btn_pressed";
        public const string INTERACTION_PERSON_REAL = "interaction_person_real";
        public const string INTERACTION_PERSON_SHADOW = "interaction_person_shadow";
        public const string INTERACTION_PERSONS = "interaction_persons";
        public const string INTERACTION_PRESS_INCIRCLE = "interaction_press_incircle";
        public const string INTERACTION_PRESS_OUTCIRCLE = "interaction_press_outcircle";
        public const string INTERACTION_PRESS_PROGRESS = "interaction_press_progress";
        public const string INTERACTION_PROGRESS = "interaction_progress";
        public const string INTERACTION_PROGRESS_BG = "interaction_progress_bg";
        public const string INTERACTION_SPRITE_BIG = "interaction_sprite_big";
        public const string INTERACTION_SPRITE_LIGHT = "interaction_sprite_light";
        public const string INTERACTION_SPRITE_SMALL = "interaction_sprite_small";
        public const string INTERACTION_WOLF_AWAKE = "interaction_wolf_awake";
        public const string INTERACTION_WOLF_SLEEP = "interaction_wolf_sleep";
        public const string LOCK = "lock";
        public const string PINK_HEART_1 = "pink_heart_1";
        public const string PINK_HEART_2 = "pink_heart_2";
        public const string PINK_HEART_3 = "pink_heart_3";
        public const string PINK_HEART_4 = "pink_heart_4";
        public const string PINK_HEART_5 = "pink_heart_5";
        public const string PINK_HEART_6 = "pink_heart_6";
        public const string PINK_HEART_7 = "pink_heart_7";
        public const string PROGRESS_RED_BG = "progress_red_bg";
        public const string PROGRESS_RED_FILL = "progress_red_fill";
        public const string INTERACTIONHEARTPRESSBUTTON = "interactionheartpressbutton";
        public const string INTERACTIONNORMALPRESSBUTTON = "interactionnormalpressbutton";
        public const string INTERACTIONPRESSBUTTON = "interactionpressbutton";
        public const string INTERACTIONTIPSBUTTON = "interactiontipsbutton";
        public const string INTERACTIONSKIP = "interactionskip";
        public const string INTERACTIONPROGRESSBAR = "interactionprogressbar";
        public const string INTERACTIONCIRCLETIMER = "interactioncircletimer";
        public const string INTERACTIONHEARTVIEW = "interactionheartview";
        public const string CROWNEFFECT = "crowneffect";
        public const string SHINYM = "shinym";
        public const string STAR = "star";
        public const string SHINY = "shiny";
        public const string CROWN_STAR = "crown_star";
        public const string WEARCROWN = "wearcrown";
        public const string CROWN_CIRCLE = "crown_circle";
        public const string CROWN_LIGHT = "crown_light";
        public const string WEAR_CROWN_1 = "wear_crown_1";
        public const string WEAR_CROWN_2 = "wear_crown_2";
        public const string WEAR_CROWN_3 = "wear_crown_3";
        public const string WEAR_CROWN_4 = "wear_crown_4";
    }
    public class Rate
    {
        public const string BundleName = "rate";
        public const string RATEPREFAB = "rateprefab";
        public const string STAR = "star";
    }
    public class Repeatread
    {
        public const string BundleName = "repeatread";
        public const string REPEATITEM = "repeatitem";
        public const string REPEATREADPREFAB = "repeatreadprefab";
        public const string ICON_LOCKED = "icon_locked";
        public const string ICON_REREAD = "icon_reread";
        public const string POP_BTN_REPETITION_ = "pop_btn_repetition_";
    }
    public class Reward
    {
        public const string BundleName = "reward";
        public const string REWARDITEM = "rewarditem";
        public const string REWARDPREFAB = "rewardprefab";
        public const string DONE = "done";
        public const string REWARD_BOX = "reward_box";
        public const string REWARD_BTN_BULE = "reward_btn_bule";
        public const string REWARD_BTNBLUE_SELECT = "reward_btnblue_select";
        public const string REWARD_BTNLINE = "reward_btnline";
        public const string REWARD_BTNLINE_SELECT = "reward_btnline_select";
        public const string REWARD_BTNPURPLE = "reward_btnpurple";
        public const string REWARD_BTNPURPLE_SELECT = "reward_btnpurple_select";
        public const string REWARD_GET = "reward_get";
        public const string REWARD_ICON_GIFT_GET = "reward_icon_gift_get";
        public const string REWARD_ICON_GIFT_UNGET = "reward_icon_gift_unget";
        public const string REWARD_ICON_GIFTS = "reward_icon_gifts";
        public const string REWARD_ICON_TICKET = "reward_icon_ticket";
        public const string REWARD_ITEM_CIRCLE = "reward_item_circle";
        public const string REWARD_ITEMBG = "reward_itembg";
        public const string REWARD_PROGRESS_TOP = "reward_progress_top";
        public const string REWARD_PROGRESSBG_TOP = "reward_progressbg_top";
        public const string REWARD_TAB_SELECT = "reward_tab_select";
        public const string REWARD_TASK_HEART = "reward_task_heart";
        public const string REWARD_TIMER = "reward_timer";
        public const string REWARD_TOP_CIRCLE = "reward_top_circle";
        public const string REWARD_UNGET = "reward_unget";
        public const string REWWARD_BTNGREY = "rewward_btngrey";
    }
    public class Rewarddetail
    {
        public const string BundleName = "rewarddetail";
        public const string REWARDDETAILITEM = "rewarddetailitem";
        public const string REWARDDETAILPREFAB = "rewarddetailprefab";
        public const string REWARD_DETAILS_ITEM = "reward_details_item";
        public const string REWARD_TIPS_ITEMBG = "reward_tips_itembg";
    }
    public class Rewarddialog
    {
        public const string BundleName = "rewarddialog";
        public const string REWARDDIALOGPREFAB = "rewarddialogprefab";
        public const string LIGHT = "light";
        public const string LIGHT_STAR = "light_star";
    }
    public class Sidebar
    {
        public const string BundleName = "sidebar";
        public const string SIDEBARPREFAB = "sidebarprefab";
        public const string BG_EDIT_BOTTOM = "bg_edit_bottom";
        public const string BG_HEAD = "bg_head";
        public const string BG_HEAD_BIG = "bg_head_big";
        public const string BOX_NAME_EDIT = "box_name_edit";
        public const string BTN_EDIT = "btn_edit";
        public const string HEAD_SELECT_BG = "head_select_bg";
        public const string ICON_HEAD_SELECT = "icon_head_select";
        public const string IMG_HEAD_GET = "img_head_get";
        public const string SIDE_BAR_BG_LONG = "side_bar_bg_long";
        public const string SIDE_BAR_BG_SHORT = "side_bar_bg_short";
        public const string SIDE_BAR_BTN_PRESSED = "side_bar_btn_pressed";
        public const string SIDE_BAR_EMAIL = "side_bar_email";
        public const string SIDE_BAR_FACE = "side_bar_face";
        public const string SIDE_BAR_FB = "side_bar_fb";
        public const string SIDE_BAR_FEEDBACK = "side_bar_feedback";
        public const string SIDE_BAR_FRAME = "side_bar_frame";
        public const string SIDE_BAR_GOOGLE = "side_bar_google";
        public const string SIDE_BAR_MESSAGES = "side_bar_messages";
        public const string SIDE_BAR_RADIO = "side_bar_radio";
        public const string SIDE_BAR_RADIO_OK = "side_bar_radio_ok";
        public const string SIDE_BAR_RATE_US = "side_bar_rate_us";
        public const string SIDE_BAR_SIGN_OUT = "side_bar_sign_out";
        public const string SIDE_BAR_SIGN_OUT_PRESSED = "side_bar_sign_out_pressed";
        public const string SIDE_BAR_SUPPORT = "side_bar_support";
    }
    public class Storydetail
    {
        public const string BundleName = "storydetail";
        public const string STORYDETAILPREFAB = "storydetailprefab";
        public const string BUTTON_PAY = "button_pay";
        public const string DETAILS_ICON_BG = "details_icon_bg";
        public const string DETAILS_ICON_LIKES = "details_icon_likes";
        public const string DETAILS_ICON_LIKES_PRESSED = "details_icon_likes_pressed";
        public const string DETAILS_ICON_REPETITION_ = "details_icon_repetition_";
        public const string DETAILS_MASK = "details_mask";
        public const string FINISHED = "finished";
        public const string ICON_DAYPASS  = "icon_daypass ";
        public const string MASK_BOTTOM = "mask_bottom";
        public const string MASK_TOP = "mask_top";
        public const string UPDATING = "updating";
    }
    public class Supportcenter
    {
        public const string BundleName = "supportcenter";
        public const string SUPPORTCENTERDIALOG = "supportcenterdialog";
    }
    public class Theatre
    {
        public const string BundleName = "theatre";
        public const string STAR_00 = "star_00";
        public const string STAR_01 = "star_01";
        public const string PAYCONFIRM = "payconfirm";
        public const string TEXTURE_STAR_00 = "texture_star_00";
        public const string TEXTURE_STAR_01 = "texture_star_01";
        public const string EFFECT_EYE = "effect_eye";
        public const string EFFECT_SMOKE = "effect_smoke";
        public const string CHAPTERBEGIN = "chapterbegin";
        public const string CONFIRMLOOK = "confirmlook";
        public const string ROLESELECT = "roleselect";
        public const string DIALOGUE = "dialogue";
        public const string LETTER = "letter";
        public const string NARRATOR = "narrator";
        public const string BTN_NORMALCONFIRM = "btn_normalconfirm";
        public const string BTN_PAYCONFIRM = "btn_payconfirm";
        public const string OPTION = "option";
        public const string OPTIONGUIDE = "optionguide";
        public const string CHATITEM = "chatitem";
        public const string PHONE = "phone";
        public const string PROPSHOW = "propshow";
        public const string THEATRESETTINGDIALOG = "theatresettingdialog";
        public const string THEATRESETTINGUI = "theatresettingui";
        public const string THEATREPREFAB = "theatreprefab";
        public const string BG_TASK_FINISH = "bg_task_finish";
        public const string BTN_ADD = "btn_add";
        public const string BTN_HOME = "btn_home";
        public const string BTN_SETTING = "btn_setting";
        public const string BTN_LEFT = "btn_left";
        public const string BTN_RIGHT = "btn_right";
        public const string CHOICE_ITEM = "choice_item";
        public const string CHOOSE_BG = "choose_bg";
        public const string COLLECTED = "collected";
        public const string FEEDBACK = "feedback";
        public const string NAME_INPUT = "name_input";
        public const string OPTION_GUIDE = "option_guide";
        public const string POS_NO = "pos_no";
        public const string POS_YES = "pos_yes";
        public const string ROLE_SELECT_BG = "role_select_bg";
        public const string ROLE_SELECT_CHANGE = "role_select_change";
        public const string ARROW = "arrow";
        public const string BG_TOP_L = "bg_top_l";
        public const string BG_TOP_R = "bg_top_r";
        public const string CLICK = "click";
        public const string CLICK_PRESSED = "click_pressed";
        public const string DIALOG_BG_BOTTOM = "dialog_bg_bottom";
        public const string DIALOG_BG_CENTER = "dialog_bg_center";
        public const string EXTRA_S_BG = "extra_s_bg";
        public const string ICON_THINK = "icon_think";
        public const string NORMAL_SELECT_BG = "normal_select_bg";
        public const string OPTION_SELECT_BG = "option_select_bg";
        public const string OPTION_SELECT_CHANGE = "option_select_change";
        public const string TOUCH_TO_CONTINUE = "touch_to_continue";
        public const string ICON_FINNISH = "icon_finnish";
        public const string ICON_GUIDE_REWARD = "icon_guide_reward";
        public const string MONEY_BG = "money_bg";
        public const string BG_TOP = "bg_top";
        public const string NARRATOR_BG_BOTTOM = "narrator_bg_bottom";
        public const string NARRATOR_BG_CENTER = "narrator_bg_center";
        public const string SCENE_INFO = "scene_info";
        public const string CAMERA = "camera";
        public const string CATCH_CALL = "catch_call";
        public const string CATCH_MEDIA = "catch_media";
        public const string DECORATE_LIGHT = "decorate_light";
        public const string DIS_CALL = "dis_call";
        public const string ICON_SEND = "icon_send";
        public const string PHONE_BG = "phone_bg";
        public const string PHONE_MEDIA_MASK = "phone_media_mask";
        public const string TEXT_BG_M = "text_bg_m";
        public const string TEXT_BG_O = "text_bg_o";
        public const string BTN_FBSHARE = "btn_fbshare";
        public const string BTN_LINKSHARE = "btn_linkshare";
        public const string BTN_MORE = "btn_more";
        public const string BTN_MSGSHARE = "btn_msgshare";
        public const string MUSIC_OFF = "music_off";
        public const string MUSIC_ON = "music_on";
    }
    public class Wallet
    {
        public const string BundleName = "wallet";
        public const string WALLETITEM = "walletitem";
        public const string WALLETPREFAB = "walletprefab";
        public const string BG_COMMODITY = "bg_commodity";
        public const string BG_COMMODITY_PACKAGES = "bg_commodity_packages";
        public const string BG_COMMODITY_TICKETS = "bg_commodity_tickets";
        public const string BG_TITLE = "bg_title";
        public const string EXTRA_1 = "extra_1";
        public const string EXTRA_2 = "extra_2";
        public const string EXTRA_3 = "extra_3";
        public const string EXTRA_4 = "extra_4";
        public const string EXTRA_5 = "extra_5";
        public const string FOUTYPERCENT = "foutypercent";
        public const string SHOP_BG_DIAMAND = "shop_bg_diamand";
        public const string SHOP_TOPBAR = "shop_topbar";
        public const string SOLDOUT = "soldout";
        public const string TICKETS_1 = "tickets_1";
        public const string TICKETS_2 = "tickets_2";
        public const string TICKETS_3 = "tickets_3";
        public const string TWEENPERCENT = "tweenpercent";
        public const string WALLET_ICON_CHOICE = "wallet_icon_choice";
        public const string WALLETITEM_1 = "walletitem_1";
        public const string WALLETITEM_2 = "walletitem_2";
        public const string WALLETITEM_3 = "walletitem_3";
        public const string WALLETITEM_4 = "walletitem_4";
        public const string WALLETITEM_5 = "walletitem_5";
        public const string WALLETITEM_6 = "walletitem_6";
        public const string WALLETITEM_7 = "walletitem_7";
        public const string WALLETITEM_8 = "walletitem_8";
        public const string WALLETITEM_9 = "walletitem_9";
        public const string WALLETITEM_10 = "walletitem_10";
        public const string WALLETITEM_11 = "walletitem_11";
        public const string WALLETITEM_12 = "walletitem_12";
    }
}
